### ISSUE TITLE
VarCloner 报错

### ISSUE THREAD

**Issue by bearlord** [esd-projects/whoops-plugin#2]
启动时候报错：Error: Class 'ESD\Plugins\Whoops\Handler\VarCloner' not found in /root/esd/vendor/esd/whoops-plugin/src/Whoops/Handler/WhoopsHandler.php:130

`if (class_exists('Symfony\Component\VarDumper\Cloner\VarCloner')) {
            $thisr = new VarCloner();
......`

应该改为：$thisr = new \Symfony\Component\VarDumper\Cloner\VarCloner();

**Comment by tmtbe** [comment]
已修复
